name: class_database
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  flutter_riverpod: ^2.6.1
  cloud_firestore: ^5.6.0
  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
