// frontend/src/components/PrivacyPage.tsx
import { Link } from 'react-router-dom'

export default function PrivacyPage() {
  return (
    <div className="privacy-page">
      <Link to="/" className="privacy-back">← Back</Link>
      <h1>Privacy &amp; AI Disclosure</h1>

      <section>
        <h2>How your data is used</h2>
        <p>GradeBee helps teachers create student observation notes and report cards. To do this, we use third-party AI services:</p>
        <ul>
          <li><strong>Mistral Voxtral</strong> — transcribes your audio recordings to text.</li>
          <li><strong>Mistral AI</strong> — analyses transcripts to extract student observations and generate report card text.</li>
        </ul>
      </section>

      <section>
        <h2>Audio recordings</h2>
        <p>Audio you upload or record in the browser is sent to Mistral Voxtral for transcription and then <strong>deleted from our servers immediately</strong>. We do not retain raw recordings. The text transcript is stored so you can review and edit your notes. The microphone is only active while you are recording — never in the background.</p>
      </section>

      <section>
        <h2>Transcripts and notes</h2>
        <p>Observation notes are stored in your account until you delete them. A copy of the transcript, or of text you pasted, is kept with its job record for up to 7 days after the job is processed or cleared from your queue, then deleted automatically. They may contain student first names and classroom observations. We recommend using first names or initials rather than full names where possible.</p>
      </section>

      <section>
        <h2>AI-generated content</h2>
        <p>Report cards and observation summaries are generated by AI. All AI-generated content is labelled and should be reviewed by the teacher before being shared with parents or included in official records. <strong>GradeBee is not a medical or diagnostic tool.</strong></p>
        <p>Teachers are responsible for reviewing and approving the accuracy of all AI-generated content before sharing.</p>
      </section>

      <section>
        <h2>Data sharing and vendors</h2>
        <p>Your data is processed by Mistral AI under their{' '}
          <a href="https://legal.mistral.ai/terms/privacy-policy" target="_blank" rel="noopener noreferrer">Privacy Policy</a>.
          GradeBee enters into a Data Processing Agreement with Mistral AI. We do not sell your data to third parties.
        </p>
      </section>

      <section>
        <h2>Contact</h2>
        <p>For privacy questions, contact us at the email address on your account.</p>
      </section>
    </div>
  )
}
