name: gradebee_models
description: Common models for GradeBee
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  lints: ^5.0.0
  test: ^1.24.0
