name: split_notes_by_student
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  dart_appwrite: ^12.0.0
  dart_openai: ^5.1.0
  gradebee_models:
    path: ../gradebee-models

dev_dependencies:
  dotenv: ^4.2.0
  lints: ^2.0.0
  test: ^1.25.14
