name: split_notes_by_student
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  dart_appwrite: ^12.0.0
  gradebee_models:
    path: ../gradebee_models

dev_dependencies:
  lints: ^2.0.0
