name: class_database
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  # firebase_core: ^3.9.0
  # cloud_firestore: ^5.6.0
  go_router: ^14.6.2
  # sqflite: ^2.4.1
  # brick_offline_first_with_supabase: ^1.2.0
  # brick_sqlite: ^3.2.0
  # brick_supabase: ^1.2.0
  # supabase_flutter: ^2.8.2
  flutter_dotenv: ^5.2.1
  appwrite: ^13.1.1
  freezed_annotation: ^2.4.4
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.0
  # brick_offline_first_with_supabase_build: ^1.1.0
  build_runner: ^2.4.14
  freezed: ^2.5.7

flutter:
  uses-material-design: true
