// Code generated by tygo. DO NOT EDIT.

//////////
// source: deps.go
/*
deps.go defines the dependency-injection interface used by HTTP handlers.
The production implementation uses SQLite repos; tests swap in stubs via the
serviceDeps variable.
*/


//////////
// source: drive_client.go
/*
drive_client.go defines the DriveClient interface and its production
implementation backed by the Google Drive SDK.
*/

/**
 * DriveFile holds the metadata returned by DriveClient.GetFileMeta.
 */
export interface DriveFile {
  MimeType: string;
}
/**
 * DriveClient abstracts the two Drive operations used by import handlers so
 * they can be tested without a real HTTP server.
 */
export type DriveClient = any;

//////////
// source: extract.go
/*
extract.go defines the Extractor interface and its OpenAI GPT implementation.
The extractor takes a transcript and student roster, returning structured
per-student extraction results with fuzzy name matching and confidence scores.
*/

/**
 * Extractor takes a transcript + student roster and returns structured extraction.
 */
export type Extractor = any;
/**
 * ExtractRequest is the input to an extraction call.
 */
export interface ExtractRequest {
  Transcript: string;
  Classes: ClassGroup[];
}
/**
 * ExtractResponse is the structured output from extraction.
 */
export interface ExtractResponse {
  students: MatchedStudent[];
  date: string;
}
/**
 * MatchedStudent is a single student extraction result.
 */
export interface MatchedStudent {
  name: string;
  class: string;
  quoted_text: string; // Extracted passages from transcript, unchanged
  confidence: number /* float64 */;
  candidates?: StudentCandidate[];
}
/**
 * StudentCandidate is a possible roster match for a low-confidence extraction.
 */
export interface StudentCandidate {
  name: string;
  class: string;
}

//////////
// source: google.go
/*
google.go provides shared HTTP error helpers and a Drive-read-only client
constructor for the /drive-import endpoint. The full Google Sheets/Docs
clients have been removed — all data is now in SQLite.
*/


//////////
// source: google_token.go
/*
google_token.go handles the GET /google-token endpoint that returns the
user's Google OAuth access token (via Clerk) so the frontend can use it
with the Google Picker API.
*/

/**
 * GoogleTokenResponse is the JSON response for GET /google-token.
 */
export interface GoogleTokenResponse {
  accessToken: string;
}

//////////
// source: handler.go
/*
handler.go is the main HTTP entrypoint for the GradeBee backend. It wires
together routing, CORS headers, request-scoped logging, and response timing.
*/


//////////
// source: logger.go
/*
logger.go initialises and exposes a package-level structured logger built on
top of the standard library's log/slog. Log level and format (text or JSON)
are controlled via LOG_LEVEL and LOG_FORMAT environment variables. A
request-scoped logger can be attached to a context and retrieved via
loggerFromContext / loggerFromRequest.
*/


//////////
// source: notes.go
/*
notes.go implements the NoteCreator interface backed by SQLite and provides
CRUD handlers for the /notes and /students/:id/notes endpoints.
*/

/**
 * NoteCreator creates notes in the database.
 */
export type NoteCreator = any;
/**
 * CreateNoteRequest is the input for creating a single student note.
 */
export interface CreateNoteRequest {
  StudentID: number /* int64 */;
  StudentName: string;
  QuotedText: string; // Extracted passages from transcript
  Transcript: string;
  Date: string; // YYYY-MM-DD
}
/**
 * CreateNoteResponse contains the created note info.
 */
export interface CreateNoteResponse {
  noteId: number /* int64 */;
}
/**
 * ListNotesResponse is the JSON envelope for handleListNotes.
 */
export interface ListNotesResponse {
  notes: Note[];
}

//////////
// source: repo_class.go

/**
 * ClassRepo provides CRUD operations for the classes table.
 */
export interface ClassRepo {
}
/**
 * Class represents a row in the classes table.
 */
export interface Class {
  id: number /* int64 */;
  userId: string;
  name: string;
  className: string;
  groupName: string;
  position: number /* int */;
  createdAt: string;
}
/**
 * ClassWithCount is a Class with its student count.
 */
export interface ClassWithCount extends Class {
  studentCount: number /* int */;
}

//////////
// source: repo_example.go

/**
 * ReportExampleRepo provides CRUD operations for the report_examples table.
 */
export interface ReportExampleRepo {
}
/**
 * DBReportExample represents a row in the report_examples table.
 * Named DBReportExample to avoid conflict with the existing Drive-backed
 * ReportExample type during the migration period.
 */
export interface DBReportExample {
  id: number /* int64 */;
  userId: string;
  name: string;
  content: string;
  status: string;
  createdAt: string;
}

//////////
// source: repo_note.go

/**
 * NoteRepo provides CRUD operations for the notes table.
 */
export interface NoteRepo {
}
/**
 * Note represents a row in the notes table.
 */
export interface Note {
  id: number /* int64 */;
  studentId: number /* int64 */;
  date: string;
  summary: string;
  transcript?: string;
  source: string;
  createdAt: string;
  updatedAt: string;
}

//////////
// source: repo_report.go

/**
 * ReportRepo provides CRUD operations for the reports table.
 */
export interface ReportRepo {
}
/**
 * Report represents a row in the reports table.
 */
export interface Report {
  id: number /* int64 */;
  studentId: number /* int64 */;
  startDate: string;
  endDate: string;
  html?: string;
  instructions?: string;
  createdAt: string;
}
/**
 * ReportSummary is the lightweight representation returned by list endpoints
 * (no HTML body, no instructions, no studentId — list is already scoped).
 */
export interface ReportSummary {
  id: number /* int64 */;
  startDate: string;
  endDate: string;
  createdAt: string;
}

//////////
// source: repo_student.go

/**
 * StudentRepo provides CRUD operations for the students table.
 */
export interface StudentRepo {
}
/**
 * Student represents a row in the students table.
 */
export interface Student {
  id: number /* int64 */;
  classId: number /* int64 */;
  name: string;
  createdAt: string;
}

//////////
// source: repo_voice_note.go

/**
 * VoiceNoteRepo provides CRUD operations for the voice_notes table.
 */
export interface VoiceNoteRepo {
}
/**
 * VoiceNote represents a row in the voice_notes table.
 */
export interface VoiceNote {
  id: number /* int64 */;
  userId: string;
  fileName: string;
  filePath: string;
  processedAt?: string;
  createdAt: string;
}

//////////
// source: report_example_drive_import.go
/*
report_example_drive_import.go handles the POST /drive-import-example endpoint that
downloads a Google Drive file, extracts text if needed, and stores it as a
report example.
*/


//////////
// source: report_example_extractor.go
/*
report_example_extractor.go extracts text from PDF/image report card examples
using GPT Vision (gpt-5.4-mini).
*/

/**
 * ExampleExtractor extracts text content from uploaded report card files.
 */
export type ExampleExtractor = any;

//////////
// source: report_example_job.go
/*
report_example_job.go defines the ExtractionJob type for async report
example text extraction (PDF/image → GPT Vision → stored text).
*/

/**
 * ExtractionJob represents an async report example text extraction job.
 */
export interface ExtractionJob {
  userId: string;
  exampleId: number /* int64 */;
  filePath: string;
  fileName: string;
  status: string;
  error?: string;
  createdAt: string;
}

//////////
// source: report_examples.go
/*
report_examples.go defines the ExampleStore interface and its DB-backed
implementation for managing example report cards.
*/

/**
 * ReportExample represents a stored example report card.
 */
export interface ReportExample {
  id: number /* int64 */;
  name: string;
  content: string;
  status: string; // "ready", "processing", "failed"
  classNames: string[];
}
/**
 * ExampleStore abstracts CRUD operations for example report cards.
 */
export type ExampleStore = any;

//////////
// source: report_examples_handler.go
/*
report_examples_handler.go handles the GET/POST/DELETE /report-examples
endpoints for managing example report cards.
*/

/**
 * ListExamplesResponse is the JSON envelope for handleListReportExamples.
 */
export interface ListExamplesResponse {
  examples: ReportExample[];
}

//////////
// source: report_generator.go
/*
report_generator.go implements the ReportGenerator interface that creates
HTML report cards using GPT and student notes from the database.
*/

/**
 * GenerateReportRequest is the input for generating a single student report.
 */
export interface GenerateReportRequest {
  StudentID: number /* int64 */;
  Student: string;
  Class: string;
  ClassName: string;
  StartDate: string; // YYYY-MM-DD
  EndDate: string; // YYYY-MM-DD
  UserID: string;
  Instructions: string;
}
/**
 * GenerateReportResponse contains the created report info.
 */
export interface GenerateReportResponse {
  reportId: number /* int64 */;
  html: string;
  createdAt: string;
}
/**
 * ReportGenerator creates report card documents.
 */
export type ReportGenerator = any;
/**
 * RegenerateReportRequest is the input for regenerating an existing report.
 */
export interface RegenerateReportRequest {
  ReportID: number /* int64 */;
  Feedback: string;
  StudentID: number /* int64 */;
  Student: string;
  Class: string;
  ClassName: string;
  StartDate: string;
  EndDate: string;
  UserID: string;
  Instructions: string;
}

//////////
// source: reports_handler.go
/*
reports_handler.go handles report generation, regeneration, listing,
fetching, and deletion endpoints.
*/

/**
 * ListReportsResponse is the JSON envelope for handleListReports.
 */
export interface ListReportsResponse {
  reports: ReportSummary[];
}
/**
 * GenerateReportsHTTPRequest is the JSON body for POST /reports.
 */
export interface GenerateReportsHTTPRequest {
  students: ReportStudentInput[];
  startDate: string;
  endDate: string;
  instructions: string;
}
/**
 * ReportStudentInput identifies a student in a generate-reports request.
 */
export interface ReportStudentInput {
  studentId: number /* int64 */;
  name: string;
  class: string;
}
/**
 * ReportResult is the per-student result in a generate/regenerate response.
 */
export interface ReportResult {
  id: number /* int64 */;
  studentId: number /* int64 */;
  student: string;
  class: string;
  html: string;
  startDate: string;
  endDate: string;
  createdAt: string;
}
/**
 * GenerateReportsHTTPResponse is the JSON response for POST /reports.
 */
export interface GenerateReportsHTTPResponse {
  reports: ReportResult[];
  error?: string;
}
/**
 * RegenerateReportHTTPRequest is the JSON body for POST /reports/:id/regenerate.
 */
export interface RegenerateReportHTTPRequest {
  feedback: string;
}
/**
 * ReportDetail is the response for GET /reports/:id — includes student/class names.
 */
export interface ReportDetail extends ReportResult {
  instructions?: string;
}

//////////
// source: roster.go
/*
roster.go defines the Roster interface and its DB-backed implementation.
The Roster is used by the upload processing pipeline to get class names
(for Whisper prompts) and student lists (for extraction matching).
*/

/**
 * Roster abstracts read access to the user's student roster.
 */
export type Roster = any;

//////////
// source: students.go
/*
students.go handles the GET /students endpoint and CRUD handlers for
classes and students. Student data is stored in SQLite.
*/

/**
 * ListClassesResponse is the JSON envelope for handleListClasses.
 */
export interface ListClassesResponse {
  classes: ClassWithCount[];
}
/**
 * ListStudentsResponse is the JSON envelope for handleListStudents.
 */
export interface ListStudentsResponse {
  students: Student[];
}
/**
 * Response types for the students API.
 */
export interface StudentsResponse {
  classes: ClassGroupResponse[];
}
export interface ClassGroupResponse {
  id: number /* int64 */;
  name: string;
  studentCount: number /* int */;
  students: StudentResponse[];
}
export interface StudentResponse {
  id: number /* int64 */;
  name: string;
}
/**
 * Internal types used by the extractor and roster (no IDs needed).
 */
export interface ClassGroup {
  name: string;
  students: ClassStudent[];
}
export interface ClassStudent {
  name: string;
}

//////////
// source: text_notes.go
/*
text_notes.go handles POST /text-notes/upload — accepts pasted text,
creates a voice_notes row (with no audio file), and dispatches a job
that skips transcription and goes straight to extraction.
*/


//////////
// source: transcriber.go
/*
transcriber.go defines the Transcriber interface and its production
implementation backed by the OpenAI Whisper API.
*/

/**
 * Transcriber abstracts audio-to-text transcription for testability.
 */
export type Transcriber = any;

//////////
// source: voice_note_drive_import.go
/*
voice_note_drive_import.go handles POST /voice-notes/drive-import — downloads a Google Drive file, saves it to local disk, and dispatches an async processing job.
*/

/**
 * DriveImportRequest is the JSON request body for POST /voice-notes/drive-import.
 */
export interface DriveImportRequest {
  fileId: string;
  fileName: string;
}
/**
 * DriveImportResponse is the JSON response for POST /voice-notes/drive-import.
 */
export interface DriveImportResponse {
  uploadId: number /* int64 */;
  fileName: string;
}

//////////
// source: voice_note_job.go
/*
voice_note_job.go defines the VoiceNoteJob type and status constants
for async voice note processing (transcribe → extract → create notes).
*/

/**
 * Job status constants for voice note processing.
 */
export const JobStatusQueued = "queued";
/**
 * Job status constants for voice note processing.
 */
export const JobStatusTranscribing = "transcribing";
/**
 * Job status constants for voice note processing.
 */
export const JobStatusExtracting = "extracting";
/**
 * Job status constants for voice note processing.
 */
export const JobStatusCreatingNotes = "creating_notes";
/**
 * Job status constants for voice note processing.
 */
export const JobStatusDone = "done";
/**
 * Job status constants for voice note processing.
 */
export const JobStatusFailed = "failed";
/**
 * NoteLink pairs a student name with the ID of the created note.
 */
export interface NoteLink {
  name: string;
  noteId: number /* int64 */;
  studentId: number /* int64 */;
  className: string;
}
/**
 * VoiceNoteJob represents an async voice note processing job.
 */
export interface VoiceNoteJob {
  userId: string;
  uploadId: number /* int64 */;
  filePath: string;
  fileName: string;
  mimeType: string;
  source: string;
  transcript?: string;
  status: string;
  createdAt: string;
  noteLinks?: NoteLink[];
  error?: string;
  failedAt?: string;
}

//////////
// source: voice_note_jobs.go
/*
voice_note_jobs.go handles the voice note job endpoints:
  GET  /voice-notes/jobs         — list jobs grouped by status
  POST /voice-notes/jobs/retry   — retry failed jobs
  POST /voice-notes/jobs/dismiss — dismiss completed/failed jobs
*/

/**
 * JobListResponse groups jobs by their processing state.
 */
export interface JobListResponse {
  active: VoiceNoteJob[];
  failed: VoiceNoteJob[];
  done: VoiceNoteJob[];
}

//////////
// source: voice_note_process.go
/*
voice_note_process.go implements the voice note processing pipeline
(transcribe → extract → create notes). Called by MemQueue workers.
*/


//////////
// source: voice_note_upload.go
/*
voice_note_upload.go handles POST /voice-notes/upload — receives an audio file via multipart/form-data, saves it to local disk, and dispatches an async processing job.
*/

/**
 * UploadResponse is the JSON response for POST /upload.
 */
export interface UploadResponse {
  uploadId: number /* int64 */;
  fileName: string;
}
