// Code generated by tygo. DO NOT EDIT.

//////////
// source: aliases.go
/*
aliases.go implements HTTP handlers for student alias management.
GET    /api/students/{id}/aliases             → list aliases
POST   /api/students/{id}/aliases             → add alias
DELETE /api/students/{id}/aliases/{aliasId}   → remove alias
*/

/**
 * AliasResponse is the JSON response for a single alias.
 */
export interface AliasResponse {
  id: number /* int64 */;
  studentId: number /* int64 */;
  alias: string;
  createdAt: string;
}

//////////
// source: auth.go
/*
auth.go provides helpers for retrieving authenticated user information from
Clerk: the Google OAuth access token for Drive/Sheets, and org-level helpers
for extracting the active Clerk Organization ID and role (Phase 1 tenancy).
*/


//////////
// source: deps.go
/*
deps.go defines the dependency-injection interface used by HTTP handlers.
The production implementation uses SQLite repos; tests swap in stubs via the
serviceDeps variable.
*/


//////////
// source: drive_client.go
/*
drive_client.go defines the DriveClient interface and its production
implementation backed by the Google Drive SDK.
*/

/**
 * DriveFile holds the metadata returned by DriveClient.GetFileMeta.
 */
export interface DriveFile {
  MimeType: string;
}
/**
 * DriveClient abstracts the two Drive operations used by import handlers so
 * they can be tested without a real HTTP server.
 */
export type DriveClient = any;

//////////
// source: errors_http.go
/*
errors_http.go holds the HTTP error-response contract: the apiError type that
carries a status through the call stack, and the writers that turn any error
into a JSON body without leaking internal text to the caller.
*/


//////////
// source: feedback_handler.go
/*
feedback_handler.go handles POST /api/feedback for explicit thumbs ratings
on generated reports and auto-extracted notes.
*/


//////////
// source: google_token.go
/*
google_token.go handles the GET /google-token endpoint that returns the
user's Google OAuth access token (via Clerk) so the frontend can use it
with the Google Picker API.
*/

/**
 * GoogleTokenResponse is the JSON response for GET /google-token.
 */
export interface GoogleTokenResponse {
  accessToken: string;
}

//////////
// source: handler.go
/*
handler.go is the main HTTP entrypoint for the GradeBee backend. It wires
together routing, CORS headers, request-scoped logging, and response timing.
*/


//////////
// source: levels.go
/*
levels.go handles CRUD handlers for the Levels admin screen. Levels are
Group-owned: reads and writes are scoped to the caller's active Clerk
Organization (see auth.go). Only an Admin may create, rename, delete a
Level, or edit its Report Instructions — Teachers get a read-only list.
*/

/**
 * ListLevelsResponse is the JSON envelope for handleListLevels.
 */
export interface ListLevelsResponse {
  levels: Level[];
}

//////////
// source: llm_provider.go
/*
llm_provider.go defines the LLMProvider abstraction that backs all LLM call
sites (extraction, report generation, vision, transcription). Two production
implementations exist: openaiProvider and mistralProvider.
*/

/**
 * LLMTask identifies a specific use case for a model selection lookup.
 */
export type LLMTask = string;
export const LLMTaskExtraction: LLMTask = "extraction";
export const LLMTaskReport: LLMTask = "report";
export const LLMTaskVision: LLMTask = "vision";
export const LLMTaskTranscription: LLMTask = "transcription";
/**
 * ChatJSONRequest is input to a structured-JSON chat call.
 */
export interface ChatJSONRequest {
  SystemPrompt: string;
  UserPrompt: string;
  SchemaName: string;
  Schema: any /* json.RawMessage */;
}
/**
 * ChatTextRequest is input to a free-form text chat call.
 */
export interface ChatTextRequest {
  UserPrompt: string;
}
/**
 * VisionRequest is input to a multimodal vision call.
 */
export interface VisionRequest {
  Prompt: string;
  MediaType: string; // e.g. "image/jpeg"
  ImageData: string /* []byte */; // raw image bytes
  /**
   * JSON schema for structured output
   */
  SchemaName: string;
  Schema: any /* json.RawMessage */;
}
/**
 * TranscribeRequest is input to an audio transcription call.
 */
export interface TranscribeRequest {
  Filename: string;
  Audio: any /* io.Reader */;
  ContextBias: string[];
}
/**
 * TranscribeResponse is the output of a transcription call.
 */
export interface TranscribeResponse {
  Text: string;
}
/**
 * LLMProvider abstracts a single LLM backend (OpenAI or Mistral).
 */
export type LLMProvider = any;

//////////
// source: llm_provider_mistral.go
/*
llm_provider_mistral.go implements LLMProvider backed by Mistral.
Chat and vision use the OpenAI-compatible endpoint via go-openai.
Transcription uses the ZaguanLabs mistral-go/v2/sdk for Voxtral support.
*/


//////////
// source: llm_provider_openai.go
/*
llm_provider_openai.go implements LLMProvider backed by OpenAI.
*/


//////////
// source: logger.go
/*
logger.go initialises and exposes a package-level structured logger built on
top of the standard library's log/slog. Log level and format (text or JSON)
are controlled via LOG_LEVEL and LOG_FORMAT environment variables.

When SENTRY_DSN is set, InitLogger wires a sentryslog handler alongside the
stdout handler so that all structured log records are forwarded to Sentry
Logs. Error/Fatal records are also captured as Sentry events (Issues) by
default sentryslog behaviour.

A request-scoped logger can be attached to a context and retrieved via
loggerFromContext / loggerFromRequest.
*/


//////////
// source: match.go
/*
match.go resolves a spoken label ("Levy", "Zachariah", "As a Xand") to a
student in one class.

The pipeline does not use it. Today's extractor is shown the roster and
returns roster names itself (extract.go), so the only resolution left there
is an id lookup. This is the second pass: when a recording reached no child
and the teacher picks a class on the done card, handleAssembleNotes re-runs
every spoken label against that class's roster — the labels are canonical
against the roster the model was shown, which on that recording was the
wrong one. It is pure, so match_test.go pins it against the eval fixtures'
own rosters with no model run, and #125's two-pass contract resolves
against it directly.

Resolution order, measured in research rounds 5 and 9:

 1. Exact match on a folded name or alias wins outright: no threshold, no
    margin. An alias is the teacher's override and must never lose to a
    heuristic. Two students sharing the string is a real tie → nobody.
 2. Otherwise exact match on a whitespace-separated part of a name
    (#111): a teacher says `Emma`, and against `Emma Torres` whole that
    scores 0.40, so the child got no note at all. Parts come after the
    typed strings so an alias never ties with a first name derived from
    another child's name; two children sharing a first name is still a
    tie. Aliases are not split — the teacher typed them as spoken. The
    stop-list applies from here on: the teacher typed rule 1's strings,
    the matcher derived these, and `He` is a part of `Wei He`.
 3. Otherwise normalised Levenshtein over every name, part and alias, a
    student's score being the best of their strings. Three gates, all
    required: the label is not a pronoun; score >= 0.50; margin >= 0.15
    over the best score of a *different* student. Parts under three
    runes — `de`, an initial — sit this round out: any three-letter label
    one edit away scores 0.67 against them.

A number gates the fuzzy score (#111). Voxtral writes a spoken number as
a digit, so `Arthur 1` on the roster is exact as spoken. A child whose
name carries a number scores 0 against a label carrying a different
one: with `Arthur 1` and `Arthur 2` in one class, `Artur 2` scores 0.86
against both stems and would tie on the margin; gated, it meets
`Arthur 2` alone. A bare `Arthur` carries no number, meets both, and
ties. A child whose name carries no number is never gated.

Breaking a tie by roster order would reproduce the root cause inside Go.
*/


//////////
// source: notes.go
/*
notes.go implements the NoteCreator interface backed by SQLite and provides
CRUD handlers for the /notes and /students/:id/notes endpoints.
*/

/**
 * NoteSourceAuto: written by the extraction pipeline end to end.
 */
export const NoteSourceAuto = "auto";
/**
 * NoteSourceReviewed: the model wrote the text, the teacher supplied only
 * the who — a recording re-assembled against a class picked on the done
 * card.
 */
export const NoteSourceReviewed = "reviewed";
/**
 * NoteSourceManual: typed by the teacher.
 */
export const NoteSourceManual = "manual";
/**
 * NoteCreator creates notes in the database.
 */
export type NoteCreator = any;
/**
 * CreateNoteRequest is the input for creating a single student note.
 */
export interface CreateNoteRequest {
  StudentID: number /* int64 */;
  StudentName: string;
  QuotedText: string; // Extracted passages from transcript
  Transcript: string;
  Date: string; // YYYY-MM-DD
  ModelVersion: string; // LLM model ID that produced this note (empty = NULL)
  /**
   * Source is a NoteSource* value; empty means NoteSourceAuto, so a caller
   * that does not care cannot write "" into the column.
   */
  Source: string;
}
/**
 * CreateNoteResponse contains the created note info.
 */
export interface CreateNoteResponse {
  noteId: number /* int64 */;
}
/**
 * ListNotesResponse is the JSON envelope for handleListNotes.
 */
export interface ListNotesResponse {
  notes: Note[];
}

//////////
// source: prompts_version.go
/*
prompts_version.go provides deterministic hashes for prompt templates so
every generated note and report row can be stamped with the prompt version
that produced it.  This enables production quality drops to be correlated to
specific prompt or model changes.

# How it works

Static template strings are defined here as package-level consts.  At init()
time each string is hashed (SHA-256, first 12 hex chars) with a
PromptVersionTag prefix so that non-template logic changes can be captured
by manually bumping the tag.

The builder functions in extract.go and report_prompt.go still live there and
interpolate dynamic values (roster, notes, feedback) into the
templates.  Hashing the static portion is a reasonable proxy: substantive
changes almost always touch the static text.
*/

/**
 * PromptVersionTag is bumped manually when non-template logic changes (e.g.
 * branching behaviour inside builder functions that hashing the template alone
 * would not catch).  Format: monotonic integer as string.
 * 6: #127 added "" to pass 1's enum. Only the schema changed, so
 * ExtractionPromptHash could not move on its own — and it is stamped into every
 * note row and every recovery log line.
 * The tag is shared, so a bump re-stamps ReportPromptHash too even when no
 * report template moved. Report rows written before and after this bump carry
 * different hashes for identical prompts; nothing is keyed on it beyond the
 * stamp, so this only means a quality readout grouped by hash shows one prompt
 * in two buckets.
 */
export const PromptVersionTag = "6";

//////////
// source: repo_class.go

/**
 * ClassRepo provides CRUD operations for the classes table.
 */
export interface ClassRepo {
}
/**
 * Class represents a row in the classes table. Name and LevelName are not
 * stored — both are derived from the referenced Level's name, so renaming a
 * Level immediately changes every Class's display name.
 */
export interface Class {
  id: number /* int64 */;
  userId: string;
  name: string;
  levelId: number /* int64 */;
  levelName: string;
  day: string;
  timeSlot: string;
  position: number /* int */;
  createdAt: string;
}
/**
 * ClassWithCount is a Class with its student count.
 */
export interface ClassWithCount extends Class {
  studentCount: number /* int */;
}
/**
 * ClassWithStudents is a Class with its students, each with aliases loaded.
 */
export interface ClassWithStudents {
  Class: Class;
  /**
   * Students is ordered by name, nil when the class has none; each
   * student's Aliases is non-nil and ordered by alias.
   */
  Students: Student[];
}

//////////
// source: repo_errors.go

/**
 * ErrDuplicateAlias is returned by AddAlias when the alias collides with an
 * existing student name or alias in the same class. ConflictStudentName holds
 * the canonical name of the student who owns the conflicting value, so the
 * handler can include it in the 409 response.
 */
export interface ErrDuplicateAlias {
  ConflictStudentName: string;
}
/**
 * ErrDuplicateStudentName is returned by Move when the student's canonical
 * name collides with an existing student's name or alias in the target
 * class. ConflictName holds the colliding name so the handler can name it
 * in the 409 response.
 */
export interface ErrDuplicateStudentName {
  ConflictName: string;
}
/**
 * ErrLevelInUse is returned by LevelRepo.Delete when Classes still
 * reference the Level. Count holds how many, so the handler can tell the
 * Admin exactly how many Classes need to move first.
 */
export interface ErrLevelInUse {
  Count: number /* int */;
}

//////////
// source: repo_feedback.go
/*
repo_feedback.go provides CRUD operations for the artifact_feedback table.
Feedback rows are append-only (no UPDATE); each edit/regen/delete event
creates a new row to preserve the full signal trajectory.
*/

/**
 * ArtifactFeedbackRepo provides insert + read access to the artifact_feedback table.
 */
export interface ArtifactFeedbackRepo {
}
/**
 * ArtifactFeedback represents a single feedback event.
 */
export interface ArtifactFeedback {
  ID: number /* int64 */;
  ArtifactType: string; // 'report' | 'note'
  ArtifactID: number /* int64 */;
  Rating: string; // 'up' | 'down'
  Signal: string; // 'explicit' | 'regenerated' | 'edited' | 'deleted'
  Comment?: string; // populated for 'explicit' and 'regenerated'
  PreviousValue?: string; // populated for 'edited' and 'deleted'
  UserID: string;
  CreatedAt: string;
}

//////////
// source: repo_level.go

/**
 * LevelRepo provides CRUD operations for the levels table. Every method is
 * scoped by group_id — a Level belongs to exactly one Group and is never
 * visible or reachable outside it.
 */
export interface LevelRepo {
}
/**
 * Level represents a row in the levels table.
 */
export interface Level {
  id: number /* int64 */;
  groupId: string;
  name: string;
  reportInstructions: string;
  createdAt: string;
}

//////////
// source: repo_note.go

/**
 * NoteRepo provides CRUD operations for the notes table.
 */
export interface NoteRepo {
}
/**
 * Note represents a row in the notes table.
 */
export interface Note {
  id: number /* int64 */;
  studentId: number /* int64 */;
  date: string;
  summary: string;
  transcript?: string;
  source: string;
  modelVersion?: string;
  promptHash?: string;
  createdAt: string;
  updatedAt: string;
}

//////////
// source: repo_report.go

/**
 * ReportRepo provides CRUD operations for the reports table.
 */
export interface ReportRepo {
}
/**
 * Report represents a row in the reports table.
 */
export interface Report {
  id: number /* int64 */;
  studentId: number /* int64 */;
  startDate: string;
  endDate: string;
  html?: string;
  instructions?: string;
  modelVersion?: string;
  promptHash?: string;
  createdAt: string;
}
/**
 * ReportSummary is the lightweight representation returned by list endpoints
 * (no HTML body, no instructions, no studentId — list is already scoped).
 */
export interface ReportSummary {
  id: number /* int64 */;
  startDate: string;
  endDate: string;
  createdAt: string;
}

//////////
// source: repo_student.go

/**
 * StudentRepo provides CRUD operations for the students table.
 */
export interface StudentRepo {
}
/**
 * Student represents a row in the students table.
 */
export interface Student {
  id: number /* int64 */;
  classId: number /* int64 */;
  name: string;
  createdAt: string;
  aliases: string[];
}
/**
 * StudentAlias represents a row in the student_aliases table.
 */
export interface StudentAlias {
  id: number /* int64 */;
  studentId: number /* int64 */;
  classId: number /* int64 */;
  alias: string;
  createdAt: string;
}

//////////
// source: repo_voice_note.go

/**
 * VoiceNoteRepo provides CRUD operations for the voice_notes table.
 */
export interface VoiceNoteRepo {
}
/**
 * VoiceNote represents a row in the voice_notes table.
 */
export interface VoiceNote {
  id: number /* int64 */;
  userId: string;
  fileName: string;
  filePath: string;
  processedAt?: string;
  purgedAt?: string;
  /**
   * Transcript is written by the processor once transcription succeeds, before
   * extraction, so it exists whether or not any note is created. It lives as long
   * as the row: the retention cleanup deletes both together.
   */
  transcript?: string;
  createdAt: string;
}

//////////
// source: report_generator.go
/*
report_generator.go implements the ReportGenerator interface that creates
HTML report cards using an LLMProvider and student notes from the database.
*/

/**
 * GenerateReportRequest is the input for generating a single student report.
 */
export interface GenerateReportRequest {
  StudentID: number /* int64 */;
  Student: string;
  ClassName: string;
  StartDate: string; // YYYY-MM-DD
  EndDate: string; // YYYY-MM-DD
  UserID: string;
  Instructions: string;
  ReportInstructions: string;
}
/**
 * GenerateReportResponse contains the created report info.
 */
export interface GenerateReportResponse {
  reportId: number /* int64 */;
  html: string;
  createdAt: string;
}
/**
 * ReportGenerator creates report card documents.
 */
export type ReportGenerator = any;
/**
 * RegenerateReportRequest is the input for regenerating an existing report.
 */
export interface RegenerateReportRequest {
  ReportID: number /* int64 */;
  Feedback: string;
  StudentID: number /* int64 */;
  Student: string;
  ClassName: string;
  StartDate: string;
  EndDate: string;
  UserID: string;
  Instructions: string;
  ReportInstructions: string;
}

//////////
// source: reports_handler.go
/*
reports_handler.go handles report generation, regeneration, listing,
fetching, and deletion endpoints.
*/

/**
 * ListReportsResponse is the JSON envelope for handleListReports.
 */
export interface ListReportsResponse {
  reports: ReportSummary[];
}
/**
 * GenerateReportsHTTPRequest is the JSON body for POST /reports.
 */
export interface GenerateReportsHTTPRequest {
  students: ReportStudentInput[];
  startDate: string;
  endDate: string;
  instructions: string;
}
/**
 * ReportStudentInput identifies a student in a generate-reports request.
 */
export interface ReportStudentInput {
  studentId: number /* int64 */;
  name: string;
  className: string;
}
/**
 * ReportResult is the per-student result in a generate/regenerate response.
 */
export interface ReportResult {
  id: number /* int64 */;
  studentId: number /* int64 */;
  student: string;
  className: string;
  html: string;
  startDate: string;
  endDate: string;
  createdAt: string;
}
/**
 * GenerateReportsHTTPResponse is the JSON response for POST /reports.
 */
export interface GenerateReportsHTTPResponse {
  reports: ReportResult[];
  error?: string;
}
/**
 * RegenerateReportHTTPRequest is the JSON body for POST /reports/:id/regenerate.
 */
export interface RegenerateReportHTTPRequest {
  feedback: string;
}
/**
 * ReportDetail is the response for GET /reports/:id — includes student/class names.
 */
export interface ReportDetail extends ReportResult {
  instructions?: string;
}

//////////
// source: roster.go
/*
roster.go defines the Roster interface and its DB-backed implementation.
The Roster is used by the upload processing pipeline to get class names
(for Whisper prompts) and student lists (for extraction matching).
*/

/**
 * Roster abstracts read access to the user's student roster.
 */
export type Roster = any;

//////////
// source: router.go
/*
router.go registers every /api/ route on a Go 1.22+ http.ServeMux using
method+pattern strings, so path parameters come from r.PathValue and an
unmatched path or method is a 404 rather than a prefix over-match.
*/


//////////
// source: sentry.go
/*
sentry.go initialises the Sentry SDK and exposes helpers for capturing
non-error feedback events from server-side code paths.
*/


//////////
// source: students.go
/*
students.go handles CRUD handlers for classes and students.
Student data is stored in SQLite.
*/

/**
 * ListClassesResponse is the JSON envelope for handleListClasses.
 */
export interface ListClassesResponse {
  classes: ClassWithCount[];
}
/**
 * ListStudentsResponse is the JSON envelope for handleListStudents.
 */
export interface ListStudentsResponse {
  students: Student[];
}
/**
 * Internal types used by the extractor and roster (no IDs needed).
 */
export interface ClassGroup {
  name: string;
  students: ClassStudent[];
}
export interface ClassStudent {
  name: string;
  aliases?: string[];
}

//////////
// source: text_notes.go
/*
text_notes.go handles POST /text-notes/upload — accepts pasted text,
creates a voice_notes row (with no audio file), and dispatches a job
that skips transcription and goes straight to extraction.
*/


//////////
// source: transcriber.go
/*
transcriber.go defines the Transcriber interface and its production
implementation backed by an LLMProvider. Audio-format normalisation
(3GP patching, extension fixing) lives here so both Whisper and Voxtral
benefit without either provider needing to know about audio quirks.
*/

/**
 * Transcriber abstracts audio-to-text transcription for testability.
 */
export type Transcriber = any;

//////////
// source: voice_note_assemble.go
/*
voice_note_assemble.go implements POST /api/voice-notes/{uploadId}/assemble:
the teacher picks the class the recording should have been read against, and
the notes the pipeline would have made then exist (#115).

It runs extraction's second pass itself (#127). Two recordings reach it and
one call serves both: a decline, where pass 1 could not pin a class so pass 2
never ran and this is its deferred first run; and a recording filed against
the wrong sibling class, where pass 2 ran against the wrong roster and this
runs it against the right one.

The pass and the fold are the pipeline's own — ExtractPassages and
assemblePassages — so there is one resolution path for a recording, not two.
*/

/**
 * AssembleNotesRequest is the body of the assemble call: the class the teacher
 * picked, and nothing else.
 * The card no longer posts its passages back. They were the note's visible
 * text, stamped with the extraction model's id under source `reviewed` — so a
 * caller could put words the model never wrote behind the model's name. Running
 * pass 2 here means the summaries stamped with the model's id are ones the
 * model produced in this request.
 */
export interface AssembleNotesRequest {
  className: string;
}
/**
 * AssembleNotesResponse is the done card, repainted. It carries what the job
 * JSON carries at completion, so the card renders as a normal done card whether
 * or not the job is still in the queue — and it says what the job says, so a
 * refresh does not contradict it.
 */
export interface AssembleNotesResponse {
  className: string;
  noteLinks: NoteLink[];
  passages: JobPassage[];
  /**
   * NoNotesReason is empty once a note exists; a pick that filed nothing comes
   * back with the reason the card already had, since nothing changed.
   */
  noNotesReason?: string;
  /**
   * CanPickClass gates the card's class picker, exactly as it does on the job.
   */
  canPickClass?: boolean;
}

//////////
// source: voice_note_drive_import.go
/*
voice_note_drive_import.go handles POST /voice-notes/drive-import — downloads a Google Drive file, saves it to local disk, and dispatches an async processing job.
*/

/**
 * DriveImportRequest is the JSON request body for POST /voice-notes/drive-import.
 */
export interface DriveImportRequest {
  fileId: string;
  fileName: string;
}
/**
 * DriveImportResponse is the JSON response for POST /voice-notes/drive-import.
 */
export interface DriveImportResponse {
  uploadId: number /* int64 */;
  fileName: string;
}

//////////
// source: voice_note_job.go
/*
voice_note_job.go defines the VoiceNoteJob type and status constants
for async voice note processing (transcribe → extract → create notes).
*/

/**
 * Job status constants for voice note processing.
 */
export const JobStatusQueued = "queued";
/**
 * Job status constants for voice note processing.
 */
export const JobStatusTranscribing = "transcribing";
/**
 * Job status constants for voice note processing.
 */
export const JobStatusExtracting = "extracting";
/**
 * Job status constants for voice note processing.
 */
export const JobStatusCreatingNotes = "creating_notes";
/**
 * Job status constants for voice note processing.
 */
export const JobStatusDone = "done";
/**
 * Job status constants for voice note processing.
 */
export const JobStatusFailed = "failed";
/**
 * NoNotesNobodyNamed: the recording named no child at all. Nothing to do.
 */
export const NoNotesNobodyNamed = "nobody_named";
/**
 * NoNotesClassUnclear: children were named, but no class was pinned, so
 * there was no roster to resolve them against. Saying the class and time
 * at the start of the next recording fixes it.
 */
export const NoNotesClassUnclear = "class_unclear";
/**
 * NoNotesNoNameMatched: every spoken name missed the roster. An alias fixes
 * the recurring ones; picking the class fixes a recording read against the
 * wrong roster.
 */
export const NoNotesNoNameMatched = "no_name_matched";
/**
 * NoteLink pairs a student name with the ID of the created note.
 */
export interface NoteLink {
  name: string;
  noteId: number /* int64 */;
  studentId: number /* int64 */;
  className: string;
}
/**
 * PassageKind says what a passage is about. Extraction returns all four, and
 * what the pipeline does with each is in voice_note_process.go.
 */
export type PassageKind = string;
/**
 * PassageChild: the teacher is talking about one child and says who.
 */
export const PassageChild: PassageKind = "child";
/**
 * PassageUnknown: the teacher is talking about one child, but no name was
 * spoken for them — only a pronoun, or a name matching nobody on the
 * class's roster. Its summary reaches the unattributed list, never a note.
 */
export const PassageUnknown: PassageKind = "unknown";
/**
 * PassageGroup: a statement about the class as a whole. It joins the note
 * of every child this recording already reached.
 */
export const PassageGroup: PassageKind = "group";
/**
 * PassageNone: not an observation about children — the spoken header, a
 * greeting, thinking aloud. Dropped at assembly and never put on a job, so
 * a recording holding nothing but a header still reads as nobody named
 * rather than offering the class picker over one empty passage.
 */
export const PassageNone: PassageKind = "none";
/**
 * JobPassage is one stretch of the recording as the pipeline read it, on the
 * wire for the done card. It is ExtractedPassage in camelCase, minus nothing:
 * the two types are separate because one is the model's contract and the other
 * is this API's, and a single struct cannot carry both spellings.
 */
export interface JobPassage {
  kind: PassageKind;
  /**
   * SpokenLabels is each name this passage is about, as the extraction model
   * wrote it. The picker hands them straight back to
   * POST /api/voice-notes/{uploadId}/assemble, which re-resolves them against
   * a class the teacher chose — without them the second run has nothing to
   * match. They go to the teacher who spoke them, never to telemetry
   * (docs/adr/0003).
   */
  spokenLabels?: string[];
  /**
   * Student is the roster name the passage reached, empty when it reached
   * nobody. That is what makes a recording pickable: every passage empty
   * means no child got a note.
   */
  student?: string;
  /**
   * Summary is the text a note built from this passage holds.
   */
  summary: string;
}
/**
 * VoiceNoteJob represents an async voice note processing job.
 */
export interface VoiceNoteJob {
  userId: string;
  uploadId: number /* int64 */;
  filePath: string;
  fileName: string;
  mimeType: string;
  source: string;
  transcript?: string;
  status: string;
  createdAt: string;
  noteLinks?: NoteLink[];
  /**
   * ClassName is the class the notes were filed under; "" when none was. It
   * and Passages are set at completion and absent on jobs done before they
   * existed.
   */
  className?: string;
  passages?: JobPassage[];
  /**
   * NoNotesReason is set only on a done job that created no note, to one of
   * the NoNotes* constants. Empty whenever a note was created. It says WHY,
   * and nothing else: it is not the card's instruction about what to offer.
   */
  noNotesReason?: string;
  /**
   * CanPickClass says whether picking a class could still rescue this
   * recording, and it is the card's gate for the class picker.
   * Separate from NoNotesReason on purpose. The two answer different
   * questions — a cause and an affordance — and folding them left the card
   * deciding an affordance by listing the causes it knew about, so a new
   * cause silently removed the picker. It also forced the assemble handler to
   * name a cause it could not know in order to keep the picker up. The server
   * decides this; the card obeys it.
   */
  canPickClass?: boolean;
  error?: string;
  failedAt?: string;
}

//////////
// source: voice_note_jobs.go
/*
voice_note_jobs.go handles the voice note job endpoints:

	GET  /voice-notes/jobs         — list jobs grouped by status
	POST /voice-notes/jobs/retry   — retry failed jobs
	POST /voice-notes/jobs/dismiss — dismiss completed/failed jobs
*/

/**
 * JobListResponse groups jobs by their processing state.
 */
export interface JobListResponse {
  active: VoiceNoteJob[];
  failed: VoiceNoteJob[];
  done: VoiceNoteJob[];
}

//////////
// source: voice_note_passages.go
/*
voice_note_passages.go folds the passages extraction returned into the notes
a recording produces and the passage list its done card carries.

Pure: no repo, no model, no clock. The pipeline (voice_note_process.go) does
the I/O around it, and the rules live here because they are the whole of
what a recording means — which stretch of speech reaches which child, and
which reaches nobody.
*/


//////////
// source: voice_note_upload.go
/*
voice_note_upload.go handles POST /voice-notes/upload — receives an audio file via multipart/form-data, saves it to local disk, and dispatches an async processing job.
*/

/**
 * UploadResponse is the JSON response for POST /upload.
 */
export interface UploadResponse {
  uploadId: number /* int64 */;
  fileName: string;
}
